# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\KP\Github\neurabotMicroscanner-main\Python\scanner_v3_fix.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MicroscannerTest(object):
    def setupUi(self, MicroscannerTest):
        MicroscannerTest.setObjectName("MicroscannerTest")
        MicroscannerTest.setEnabled(True)
        MicroscannerTest.resize(1650, 1020)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setKerning(True)
        MicroscannerTest.setFont(font)
        MicroscannerTest.setWindowTitle("Microscanner Test")
        MicroscannerTest.setLayoutDirection(QtCore.Qt.LeftToRight)
        MicroscannerTest.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MicroscannerTest)
        self.centralwidget.setObjectName("centralwidget")
        self.capturelbl = QtWidgets.QLabel(self.centralwidget)
        self.capturelbl.setGeometry(QtCore.QRect(380, 20, 951, 821))
        self.capturelbl.setFrameShape(QtWidgets.QFrame.Box)
        self.capturelbl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.capturelbl.setLineWidth(1)
        self.capturelbl.setText("")
        self.capturelbl.setObjectName("capturelbl")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1360, 10, 271, 931))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.openCam_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.openCam_btn.setGeometry(QtCore.QRect(0, 29, 261, 31))
        self.openCam_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.openCam_btn.setObjectName("openCam_btn")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 70, 271, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.exposureMode = QtWidgets.QComboBox(self.groupBox_4)
        self.exposureMode.setGeometry(QtCore.QRect(0, 30, 261, 30))
        self.exposureMode.setObjectName("exposureMode")
        self.exposure_slider = QtWidgets.QSlider(self.groupBox_4)
        self.exposure_slider.setGeometry(QtCore.QRect(0, 70, 261, 22))
        self.exposure_slider.setProperty("value", 40)
        self.exposure_slider.setOrientation(QtCore.Qt.Horizontal)
        self.exposure_slider.setObjectName("exposure_slider")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 170, 271, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.WBMode = QtWidgets.QComboBox(self.groupBox_5)
        self.WBMode.setGeometry(QtCore.QRect(0, 30, 261, 30))
        self.WBMode.setObjectName("WBMode")
        self.R_slider = QtWidgets.QSlider(self.groupBox_5)
        self.R_slider.setGeometry(QtCore.QRect(29, 70, 221, 22))
        self.R_slider.setOrientation(QtCore.Qt.Horizontal)
        self.R_slider.setObjectName("R_slider")
        self.G_slider = QtWidgets.QSlider(self.groupBox_5)
        self.G_slider.setGeometry(QtCore.QRect(29, 100, 221, 22))
        self.G_slider.setOrientation(QtCore.Qt.Horizontal)
        self.G_slider.setObjectName("G_slider")
        self.B_slider = QtWidgets.QSlider(self.groupBox_5)
        self.B_slider.setGeometry(QtCore.QRect(30, 130, 221, 22))
        self.B_slider.setOrientation(QtCore.Qt.Horizontal)
        self.B_slider.setObjectName("B_slider")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 16, 16))
        self.label_9.setObjectName("label_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 340, 271, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.brightness_slider = QtWidgets.QSlider(self.groupBox_6)
        self.brightness_slider.setGeometry(QtCore.QRect(10, 30, 241, 22))
        self.brightness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_slider.setObjectName("brightness_slider")
        self.digitalShift_slider = QtWidgets.QSlider(self.groupBox_6)
        self.digitalShift_slider.setGeometry(QtCore.QRect(10, 90, 241, 22))
        self.digitalShift_slider.setOrientation(QtCore.Qt.Horizontal)
        self.digitalShift_slider.setObjectName("digitalShift_slider")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 131, 20))
        self.label_3.setObjectName("label_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 460, 271, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gainRaw_slider = QtWidgets.QSlider(self.groupBox_7)
        self.gainRaw_slider.setGeometry(QtCore.QRect(10, 40, 241, 22))
        self.gainRaw_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gainRaw_slider.setObjectName("gainRaw_slider")
        self.gamma_slider = QtWidgets.QSlider(self.groupBox_7)
        self.gamma_slider.setGeometry(QtCore.QRect(10, 100, 241, 22))
        self.gamma_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gamma_slider.setObjectName("gamma_slider")
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setGeometry(QtCore.QRect(0, 70, 131, 20))
        self.label_5.setObjectName("label_5")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 600, 271, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.denoising_slider = QtWidgets.QSlider(self.groupBox_8)
        self.denoising_slider.setGeometry(QtCore.QRect(10, 90, 241, 22))
        self.denoising_slider.setOrientation(QtCore.Qt.Horizontal)
        self.denoising_slider.setObjectName("denoising_slider")
        self.denoising_lbl = QtWidgets.QLabel(self.groupBox_8)
        self.denoising_lbl.setGeometry(QtCore.QRect(10, 60, 131, 20))
        self.denoising_lbl.setObjectName("denoising_lbl")
        self.denoising_cb = QtWidgets.QCheckBox(self.groupBox_8)
        self.denoising_cb.setGeometry(QtCore.QRect(10, 30, 70, 17))
        self.denoising_cb.setObjectName("denoising_cb")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 730, 271, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.sharpness_slider = QtWidgets.QSlider(self.groupBox_9)
        self.sharpness_slider.setGeometry(QtCore.QRect(10, 100, 241, 22))
        self.sharpness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sharpness_slider.setObjectName("sharpness_slider")
        self.denoising_slider_3 = QtWidgets.QLabel(self.groupBox_9)
        self.denoising_slider_3.setGeometry(QtCore.QRect(10, 70, 131, 20))
        self.denoising_slider_3.setObjectName("denoising_slider_3")
        self.sharpness_cb = QtWidgets.QCheckBox(self.groupBox_9)
        self.sharpness_cb.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.sharpness_cb.setObjectName("sharpness_cb")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 10, 311, 181))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setToolTip("")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.status_txt = QtWidgets.QTextEdit(self.groupBox_3)
        self.status_txt.setEnabled(True)
        self.status_txt.setGeometry(QtCore.QRect(0, 110, 231, 60))
        self.status_txt.setToolTip("")
        self.status_txt.setAutoFillBackground(False)
        self.status_txt.setReadOnly(True)
        self.status_txt.setObjectName("status_txt")
        self.comCombo = QtWidgets.QComboBox(self.groupBox_3)
        self.comCombo.setEnabled(True)
        self.comCombo.setGeometry(QtCore.QRect(0, 30, 231, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comCombo.setFont(font)
        self.comCombo.setToolTip("")
        self.comCombo.setWhatsThis("")
        self.comCombo.setCurrentText("")
        self.comCombo.setObjectName("comCombo")
        self.connect_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.connect_btn.setEnabled(True)
        self.connect_btn.setGeometry(QtCore.QRect(100, 70, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.connect_btn.setFont(font)
        self.connect_btn.setToolTip("")
        self.connect_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.connect_btn.setObjectName("connect_btn")
        self.comRefresh_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.comRefresh_btn.setEnabled(True)
        self.comRefresh_btn.setGeometry(QtCore.QRect(0, 70, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comRefresh_btn.setFont(font)
        self.comRefresh_btn.setToolTip("")
        self.comRefresh_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.comRefresh_btn.setObjectName("comRefresh_btn")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(160, 200, 181, 131))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.namaSlide_text = QtWidgets.QLineEdit(self.groupBox)
        self.namaSlide_text.setGeometry(QtCore.QRect(0, 30, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.namaSlide_text.setFont(font)
        self.namaSlide_text.setObjectName("namaSlide_text")
        self.namaSlide_btn = QtWidgets.QPushButton(self.groupBox)
        self.namaSlide_btn.setGeometry(QtCore.QRect(0, 70, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.namaSlide_btn.setFont(font)
        self.namaSlide_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.namaSlide_btn.setObjectName("namaSlide_btn")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(650, 850, 461, 111))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_10.setFlat(True)
        self.groupBox_10.setObjectName("groupBox_10")
        self.Row_lbl = QtWidgets.QLabel(self.groupBox_10)
        self.Row_lbl.setGeometry(QtCore.QRect(10, 50, 80, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Row_lbl.setFont(font)
        self.Row_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Row_lbl.setObjectName("Row_lbl")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.Col_lbl = QtWidgets.QLabel(self.groupBox_10)
        self.Col_lbl.setGeometry(QtCore.QRect(130, 50, 80, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Col_lbl.setFont(font)
        self.Col_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Col_lbl.setObjectName("Col_lbl")
        self.label_16 = QtWidgets.QLabel(self.groupBox_10)
        self.label_16.setGeometry(QtCore.QRect(130, 30, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.totalimg_lbl = QtWidgets.QLabel(self.groupBox_10)
        self.totalimg_lbl.setGeometry(QtCore.QRect(240, 50, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.totalimg_lbl.setFont(font)
        self.totalimg_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.totalimg_lbl.setObjectName("totalimg_lbl")
        self.label_19 = QtWidgets.QLabel(self.groupBox_10)
        self.label_19.setGeometry(QtCore.QRect(240, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_27 = QtWidgets.QLabel(self.groupBox_10)
        self.label_27.setGeometry(QtCore.QRect(330, 30, 140, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.currImg_lbl = QtWidgets.QLabel(self.groupBox_10)
        self.currImg_lbl.setGeometry(QtCore.QRect(340, 50, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.currImg_lbl.setFont(font)
        self.currImg_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.currImg_lbl.setObjectName("currImg_lbl")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setEnabled(True)
        self.start_btn.setGeometry(QtCore.QRect(280, 40, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_btn.setFont(font)
        self.start_btn.setToolTip("")
        self.start_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.start_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_btn.setIcon(icon)
        self.start_btn.setIconSize(QtCore.QSize(55, 55))
        self.start_btn.setObjectName("start_btn")
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 320, 311, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.r_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.r_btn.setGeometry(QtCore.QRect(210, 100, 101, 51))
        self.r_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}\n"
"\n"
"")
        self.r_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/kanan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.r_btn.setIcon(icon1)
        self.r_btn.setObjectName("r_btn")
        self.u_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.u_btn.setGeometry(QtCore.QRect(110, 30, 93, 51))
        self.u_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.u_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.u_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/atas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.u_btn.setIcon(icon2)
        self.u_btn.setObjectName("u_btn")
        self.d_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.d_btn.setGeometry(QtCore.QRect(110, 170, 93, 51))
        self.d_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.d_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/bawah.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.d_btn.setIcon(icon3)
        self.d_btn.setObjectName("d_btn")
        self.l_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.l_btn.setGeometry(QtCore.QRect(0, 100, 101, 51))
        self.l_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.l_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/kiri.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.l_btn.setIcon(icon4)
        self.l_btn.setObjectName("l_btn")
        self.home_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.home_btn.setGeometry(QtCore.QRect(110, 90, 91, 71))
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.home_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.home_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon5)
        self.home_btn.setIconSize(QtCore.QSize(50, 50))
        self.home_btn.setObjectName("home_btn")
        self.ru_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.ru_btn.setGeometry(QtCore.QRect(210, 40, 101, 51))
        self.ru_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}\n"
"\n"
"")
        self.ru_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/kanan_atas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ru_btn.setIcon(icon6)
        self.ru_btn.setObjectName("ru_btn")
        self.lu_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.lu_btn.setGeometry(QtCore.QRect(0, 40, 101, 51))
        self.lu_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.lu_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/kiri_atas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lu_btn.setIcon(icon7)
        self.lu_btn.setObjectName("lu_btn")
        self.ld_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.ld_btn.setGeometry(QtCore.QRect(0, 160, 101, 51))
        self.ld_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.ld_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/kiri_bawah.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ld_btn.setIcon(icon8)
        self.ld_btn.setObjectName("ld_btn")
        self.rd_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.rd_btn.setGeometry(QtCore.QRect(210, 160, 101, 51))
        self.rd_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}\n"
"\n"
"")
        self.rd_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/kanan_bawah.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rd_btn.setIcon(icon9)
        self.rd_btn.setObjectName("rd_btn")
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setGeometry(QtCore.QRect(30, 870, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setObjectName("groupBox_13")
        self.open_btn = QtWidgets.QPushButton(self.groupBox_13)
        self.open_btn.setGeometry(QtCore.QRect(10, 40, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.open_btn.setFont(font)
        self.open_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.open_btn.setObjectName("open_btn")
        self.tiff_btn = QtWidgets.QPushButton(self.groupBox_13)
        self.tiff_btn.setGeometry(QtCore.QRect(170, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tiff_btn.setFont(font)
        self.tiff_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.tiff_btn.setObjectName("tiff_btn")
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_14.setGeometry(QtCore.QRect(30, 560, 311, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_14.setFlat(True)
        self.groupBox_14.setObjectName("groupBox_14")
        self.t_btn = QtWidgets.QPushButton(self.groupBox_14)
        self.t_btn.setGeometry(QtCore.QRect(190, 30, 101, 51))
        self.t_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.t_btn.setText("")
        self.t_btn.setIcon(icon2)
        self.t_btn.setObjectName("t_btn")
        self.b_btn = QtWidgets.QPushButton(self.groupBox_14)
        self.b_btn.setGeometry(QtCore.QRect(190, 100, 101, 51))
        self.b_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.b_btn.setText("")
        self.b_btn.setIcon(icon3)
        self.b_btn.setObjectName("b_btn")
        self.auto_btn = QtWidgets.QPushButton(self.groupBox_14)
        self.auto_btn.setGeometry(QtCore.QRect(20, 60, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.auto_btn.setFont(font)
        self.auto_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.auto_btn.setObjectName("auto_btn")
        self.startPoint_btn = QtWidgets.QPushButton(self.centralwidget)
        self.startPoint_btn.setGeometry(QtCore.QRect(30, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startPoint_btn.setFont(font)
        self.startPoint_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.startPoint_btn.setObjectName("startPoint_btn")
        self.endPoint_btn = QtWidgets.QPushButton(self.centralwidget)
        self.endPoint_btn.setGeometry(QtCore.QRect(30, 270, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.endPoint_btn.setFont(font)
        self.endPoint_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.endPoint_btn.setObjectName("endPoint_btn")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setEnabled(True)
        self.stop_btn.setGeometry(QtCore.QRect(280, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stop_btn.setFont(font)
        self.stop_btn.setToolTip("")
        self.stop_btn.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    border-top: 3px solid #aaaaaa;\n"
"    border-left: 3px solid #aaaaaa;\n"
"    border-right: 3px solid #aaaaaa;\n"
"    border-bottom: 3px solid #aaaaaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: solid #aaaaaa;\n"
"    \n"
"}")
        self.stop_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("d:\\KP\\Github\\neurabotMicroscanner-main\\Python\\../capture/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_btn.setIcon(icon10)
        self.stop_btn.setIconSize(QtCore.QSize(55, 55))
        self.stop_btn.setObjectName("stop_btn")
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(20, 720, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_15.setFlat(True)
        self.groupBox_15.setObjectName("groupBox_15")
        self.label = QtWidgets.QLabel(self.groupBox_15)
        self.label.setGeometry(QtCore.QRect(30, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_15)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.over = QtWidgets.QComboBox(self.groupBox_15)
        self.over.setGeometry(QtCore.QRect(210, 70, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.over.setFont(font)
        self.over.setObjectName("over")
        self.delayCapture = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.delayCapture.setGeometry(QtCore.QRect(210, 30, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delayCapture.setFont(font)
        self.delayCapture.setObjectName("delayCapture")
        self.label_7 = QtWidgets.QLabel(self.groupBox_15)
        self.label_7.setGeometry(QtCore.QRect(30, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.speedScan = QtWidgets.QSpinBox(self.groupBox_15)
        self.speedScan.setGeometry(QtCore.QRect(210, 110, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.speedScan.setFont(font)
        self.speedScan.setObjectName("speedScan")
        self.groupBox_16 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_16.setGeometry(QtCore.QRect(30, 200, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_16.setFlat(True)
        self.groupBox_16.setObjectName("groupBox_16")
        self.startPoint_btn.raise_()
        self.groupBox_16.raise_()
        self.endPoint_btn.raise_()
        self.capturelbl.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.groupBox_10.raise_()
        self.start_btn.raise_()
        self.groupBox_12.raise_()
        self.groupBox_13.raise_()
        self.groupBox_14.raise_()
        self.stop_btn.raise_()
        self.groupBox_15.raise_()
        MicroscannerTest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MicroscannerTest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1650, 26))
        self.menubar.setObjectName("menubar")
        MicroscannerTest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MicroscannerTest)
        self.statusbar.setObjectName("statusbar")
        MicroscannerTest.setStatusBar(self.statusbar)

        self.retranslateUi(MicroscannerTest)
        QtCore.QMetaObject.connectSlotsByName(MicroscannerTest)

    def retranslateUi(self, MicroscannerTest):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_2.setTitle(_translate("MicroscannerTest", "Camera Setting"))
        self.openCam_btn.setText(_translate("MicroscannerTest", "Open Cam"))
        self.groupBox_4.setTitle(_translate("MicroscannerTest", "Exposure"))
        self.groupBox_5.setTitle(_translate("MicroscannerTest", "White Balance"))
        self.label_4.setText(_translate("MicroscannerTest", "R"))
        self.label_6.setText(_translate("MicroscannerTest", "G"))
        self.label_9.setText(_translate("MicroscannerTest", "B"))
        self.groupBox_6.setTitle(_translate("MicroscannerTest", "Brightness"))
        self.label_3.setText(_translate("MicroscannerTest", "DigitalShift"))
        self.groupBox_7.setTitle(_translate("MicroscannerTest", "GainRaw"))
        self.label_5.setText(_translate("MicroscannerTest", "Gamma"))
        self.groupBox_8.setTitle(_translate("MicroscannerTest", "Denoising"))
        self.denoising_lbl.setText(_translate("MicroscannerTest", "Value"))
        self.denoising_cb.setText(_translate("MicroscannerTest", "Open"))
        self.groupBox_9.setTitle(_translate("MicroscannerTest", "Sharpeness"))
        self.denoising_slider_3.setText(_translate("MicroscannerTest", "Value"))
        self.sharpness_cb.setText(_translate("MicroscannerTest", "Open"))
        self.groupBox_3.setTitle(_translate("MicroscannerTest", "Setup Serial"))
        self.connect_btn.setText(_translate("MicroscannerTest", "Connect"))
        self.comRefresh_btn.setText(_translate("MicroscannerTest", "Refresh"))
        self.groupBox.setTitle(_translate("MicroscannerTest", "Slide Name"))
        self.namaSlide_btn.setText(_translate("MicroscannerTest", "Save"))
        self.groupBox_10.setTitle(_translate("MicroscannerTest", "Scan Process"))
        self.Row_lbl.setText(_translate("MicroscannerTest", "-"))
        self.label_15.setText(_translate("MicroscannerTest", "Row"))
        self.Col_lbl.setText(_translate("MicroscannerTest", "-"))
        self.label_16.setText(_translate("MicroscannerTest", "Column"))
        self.totalimg_lbl.setText(_translate("MicroscannerTest", "-"))
        self.label_19.setText(_translate("MicroscannerTest", "Total Img"))
        self.label_27.setText(_translate("MicroscannerTest", "Scan Img"))
        self.currImg_lbl.setText(_translate("MicroscannerTest", "-"))
        self.groupBox_12.setTitle(_translate("MicroscannerTest", "Position Calibration"))
        self.groupBox_13.setTitle(_translate("MicroscannerTest", "Preparate and File"))
        self.open_btn.setText(_translate("MicroscannerTest", "Open Image"))
        self.tiff_btn.setText(_translate("MicroscannerTest", "Save To Tiff"))
        self.groupBox_14.setTitle(_translate("MicroscannerTest", "Camera Calibration"))
        self.auto_btn.setText(_translate("MicroscannerTest", "AUTOFUCUS"))
        self.startPoint_btn.setText(_translate("MicroscannerTest", "START"))
        self.endPoint_btn.setText(_translate("MicroscannerTest", "END"))
        self.groupBox_15.setTitle(_translate("MicroscannerTest", "Stiching"))
        self.label.setText(_translate("MicroscannerTest", "Delay Capture"))
        self.label_2.setText(_translate("MicroscannerTest", "Over"))
        self.label_7.setText(_translate("MicroscannerTest", "Speed Scan"))
        self.groupBox_16.setTitle(_translate("MicroscannerTest", "Position"))
